apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  
  name: my-event-broker
  namespace: poc-workshop
  
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing